server:
  port: 8080
  address:

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      maxIdle: 10
      max-active: 5
      max-wait: 10000
      validationQuery: select 1
      removeAbandoned: true
      removeAbandonedTimeout: 120
    servlet:
      multipart:
        max-file-size: 15MB
        max-request-size: 15MB